version: '3.4'

services:
    db:
        image: postgis/postgis
        ports:
            - 5432:5432
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql
        env_file:
            - .env

    backend:
        container_name: soroka-backend
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/soroka-backend
            - /soroka-backend/node_modules
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - .env

    minio:
        image: minio/minio
        ports:
        - "9000:9000"
        - "9001:9001"
        env_file:
            - .env
        command: server --console-address ":9001" /data
    
