version: '3'

services:
    db:
        image: postgres
        ports:
            - 6432:5432
        environment:
            - POSTGRES_USER=soroka
            - POSTGRES_PASSWORD=soroka
            - POSTGRES_DB=soroka
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql
    backend:
        container_name: soroka-backend
        build:
            context: .
            dockerfile: Dockerfile
        command: npm start --start;
        volumes:
            - ./:/soroka-backend/
            - ./src:/soroka-backend/src
        ports:
            - "8000:8000"
        depends_on:
            - db
