version: '3.4'

services:
    db:
        image: postgis/postgis
        expose:
            - 5432
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql
        env_file:
            - .env

    backend:
        container_name: soroka-backend
        build:
            context: .
            target: dev
        volumes:
            - ./:/soroka-backend/
            - /soroka-backend/node_modules
        ports:
            - 8000:8000
        depends_on:
            - db
