name: Deploy image on merge

concurrency: staging

on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  USERNAME: deploy
  HOST: wunder-kammer.ru
  PORT: 22
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NAME: soroka-backend-stage

jobs:
  deploy:
    name: Deploy staging
    runs-on: ubuntu-latest
    env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER_STAGE }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_STAGE }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB_STAGE }}
        DB_PORT: ${{ secrets.DB_PORT_STAGE }}
        DB_HOST: ${{ secrets.DB_HOST_STAGE }}
        DB_DIALECT: postgres
        SERVER_PORT: 8000
        ACCESS_TOKEN_LIFETIME: 300000
        REFRESH_TOKEN_LIFETIME: 3600000
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.WNDRKMR_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u dice4x4 --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}
            docker rm -f ${{ env.NAME }}
            docker run -dp 8083:8000 --network wndrnet --name ${{ env.NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.pull_request.number }}
            docker logout

